server:
  port: 8762
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chgyoo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: password
    pool:
      jedis:
        max-active: 100
        max-idle: 10
        min-idle: 0
        max-wait: 2000
    timeout: 3000ms
    database: 0
#日志配置

logging:
  config: classpath:logback-${spring.profiles.active}.xml
#mapper扫描路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.chgyoo.barret.mapper
#数据库配置
